volumes:
  pgdata:
  pgdata-test:

services:
  notify:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FROM=${FROM}
      - TO=${TO}
      - MAIL_TOKEN=${MAIL_TOKEN}
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-notify-stock}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET}
      - OAUTH_REDIRECT_URL=${OAUTH_REDIRECT_URL}
      - LOG_LEVEL=debug
      - FRONTEND_URL=${FRONTEND_URL}
      - MAIL_GUN_API_KEY=${MAIL_GUN_API_KEY}
      - MAIL_DOMAIN=${MAIL_DOMAIN}
    working_dir: /app
    command: ["server"]
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: postgres:17
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=notify-stock
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5555:5432
